branches:
  only:
    - master
language: ruby
services:
  - mysql
before_script:
  - mysql -uroot -e 'create database eol_test;'
  - cp config/secrets.sample.yml config/secrets.yml
script:
  - bin/rake db:migrate RAILS_ENV=test --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
bundler_args: --binstubs
addons:
  code_climate:
    repo_token: 7c07850ceb2c6d36b0ab6d76cbb9e64826281b805556926b8d8d6f449ce0323b
notifications:
  email:
    - developers@eol.org
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/54b78b0213d88282d445
    on_success: change
    on_failure: always
    on_start: never
