version: '2'
services:
  eol-backend-memcached:
    image: memcached
    container_name: eol-backend-memcached
    restart: always
    environment:
      - TZ=America/New_York
    command: memcached -m 4096m
    network_mode: "bridge"
  eol-backend-neo4j:
    image: neo4j
    container_name: eol-backend-neo4j
    restart: always
    environment:
      - TZ=America/New_York 
      - NEO4J_AUTH=neo4j/SomePasswordHere
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_maxSize=4G
    volumes:
      - /u/data/eol-backend-neo4j/data:/data
      - /u/data/eol-backend-neo4j/logs:/logs
      - /u/data/eol-backend-neo4j/conf:/conf
    network_mode: "bridge"
  eol-backend-mysql:
    image: mysql
    container_name: eol-backend-mysql
    restart: always
    environment:
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=EolRocks!
      - MYSQL_DATABASE=eol_web_staging
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=SuperSecretYouWillNeverKnow!
    volumes:
       - /u/data/eol-backend-mysql:/var/lib/mysql
    network_mode: "bridge"
  eol-backend-tramea:
    image: encoflife/eol-backend.tramea
    container_name: eol-backend-tramea
    restart: always
    volumes:
      - /u/data/eol-backend-tramea:/u/apps/eol_website/public/data
    depends_on:
      - eol-backend-mysql
      - eol-backend-neo4j
      - eol-backend-memcached
    links:
      - eol-backend-memcached:memcached
      - eol-backend-mysql:mysql
      - eol-backend-neo4j:neo4j
    env_file:
      - resources/staging.env
    ports:
       - 3000:3000
    network_mode: "bridge"

