version: '3.0' # NOTE: this is NOT a version of the *file*, it's a version of the config formatting to use. Keep it here.
services:
  eol-backend-elasticsearch:
    image: elasticsearch
    container_name: eol-backend-elasticsearch
    restart: always
    environment:
      - RAILS_ENV
      - TZ=America/New_York
      - bootstrap.memory_lock=true
      - cluster.name=eol-search-${RAILS_ENV}
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./templates/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/eol-backend-elasticsearch/data:/var/data/elasticsearch
      - /data/eol-backend-elasticsearch/log:/var/log/elasticsearch
    ports:
      - 9200:9200
    networks:
      - eolnet
  eol-backend-elasticsearch2:
    image: elasticsearch
    container_name: eol-backend-elasticsearch2
    restart: always
    environment:
      - RAILS_ENV
      - TZ=America/New_York
      - bootstrap.memory_lock=true
      - cluster.name=eol-search-${RAILS_ENV}
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - "discovery.zen.ping.unicast.hosts=eol-search-${RAILS_ENV}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./templates/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/eol-backend-elasticsearch/data2:/var/data/elasticsearch
      - /data/eol-backend-elasticsearch/log:/var/log/elasticsearch
    networks:
      - eolnet
  eol-backend-memcached:
    image: memcached
    container_name: eol-backend-memcached
    restart: always
    environment:
      - TZ=America/New_York
    command: memcached -m 4096m
    networks:
      - eolnet
  eol-backend-neo4j:
    image: neo4j
    container_name: eol-backend-neo4j
    restart: always
    environment:
      - TZ=America/New_York
      - NEO4J_AUTH=neo4j/SomePasswordHere
      - NEO4J_dbms_memory_pagecache_size=4G
      - NEO4J_dbms_memory_heap_maxSize=16G
    volumes:
      - /data/eol-backend-neo4j/data:/data
      - /data/eol-backend-neo4j/logs:/logs
      - ./resources/templates/neo4j.conf:/conf/neo4j.conf
    networks:
      - eolnet
  eol-backend-mysql:
    image: mysql:5.7.12
    container_name: eol-backend-mysql
    restart: always
    environment:
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=EolRocks!
      - MYSQL_DATABASE=eol_web_staging
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=SuperSecretYouWillNeverKnow!
    volumes:
       - /u/data/eol-backend-mysql:/var/lib/mysql
    networks:
      - eolnet
  eol-backend-tramea:
    build: ..
    image: eol_website
    container_name: eol-backend-tramea
    restart: always
    environment: # NOTE: see https://docs.docker.com/compose/environment-variables/ for details.
      - RAILS_ENV
      - ELASTICSEARCH_URL=elasticsearch:9200
    volumes:
      - ./resources/secrets.yml:/app/config/secrets.yml
      - /data/eol-backend-tramea:/app/public/data
      - /eol/tmp/eol_website:/tmp
    depends_on:
      - eol-backend-mysql
      - eol-backend-neo4j
      - eol-backend-memcached
      - eol-backend-elasticsearch
    links:
      - eol-backend-elasticsearch:elasticsearch
      - eol-backend-memcached:memcached
      - eol-backend-mysql:mysql
      - eol-backend-neo4j:neo4j
    ports:
       - 3000:3000
    networks:
      - eolnet
networks:
  eolnet:
    driver: bridge
