# common settings for all databases
common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: true
  wait_timeout: 300

# common settings for any development databases
devel_common: &dev
  host: localhost
  username: <%= ENV['EOL_DEVEL_DB_USERNAME'] %>
  password: <%= ENV['EOL_DEVEL_DB_PASSWORD'] %>

# common settings for all test databases
tst_common: &tst
  host: localhost
  username: <%= ENV['EOL_DEVEL_DB_USERNAME'] %>
  password: <%= ENV['EOL_DEVEL_DB_PASSWORD'] %>

#######################
development:
  <<: *common
  <<: *dev
  database: eol_website_development

############################
test: &test
  <<: *common
  <<: *tst
  database: eol_website_test

# read-write split testing:
test_master:
  <<: *common
  <<: *tst
  database: eol_website_test_master

staging:
  <<: *common
  host: <%= ENV['EOL_DATABASE_HOST'] %>
  port: <%= ENV['EOL_DATABASE_PORT'] %>
  database: <%= ENV['EOL_DATABASE_NAME'] %>
  username: <%= ENV['EOL_DATABASE_USER'] %>
  password: <%= ENV['EOL_DATABASE_PASSWORD'] %>

production:
  <<: *common
  host: <%= ENV['EOL_DATABASE_HOST'] %>
  port: <%= ENV['EOL_DATABASE_PORT'] %>
  database: <%= ENV['EOL_DATABASE_NAME'] %>
  username: <%= ENV['EOL_DATABASE_USER'] %>
  password: <%= ENV['EOL_DATABASE_PASSWORD'] %>
