# common settings for all databases
common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: true
  wait_timeout: 300
# <<<<<<< HEAD
# =======
  # local_infile: true
  # username: <%= Rails.application.secrets.db['username'] %>
  # password: <%= Rails.application.secrets.db['password'] %>
  # database: <%= Rails.application.secrets.db['name'] %>
# >>>>>>> 8dd8322811dfea6a8590010fa7863a65fb5598ab

# common settings for any development databases
development:
  <<: *common
  host: localhost
  # PLEASE DON'T PUT YOUR USER / PASS HERE (e.g.: "root"). Set your environment
  # variables.
  username: <%= ENV['EOL_DB_DEVEL_USERNAME'] %>
  password: <%= ENV['EOL_DB_DEVEL_PASSWORD'] %>
  database: eol_development

test: &test
  <<: *common
  database: eol_test
  host: localhost
  # PLEASE DON'T PUT YOUR USER / PASS HERE (e.g.: "root"). Set your environment
  # variables.
  username: <%= ENV['EOL_DB_DEVEL_USERNAME'] %>
  password: <%= ENV['EOL_DB_DEVEL_PASSWORD'] %>

staging:
  <<: *common
  host: <%= ENV['EOL_DB_HOST'] %>
  port: <%= ENV['EOL_DB_PORT'] %>
  database: <%= ENV['EOL_DB_STAGING_NAME'] %>
  username: <%= ENV['EOL_DB_STAGING_USERNAME'] %>
  password: <%= ENV['EOL_DB_STAGING_PASSWORD'] %>

production:
  <<: *common
  host: <%= ENV['EOL_DB_HOST'] %>
  port: <%= ENV['EOL_DB_PORT'] %>
  database: <%= ENV['EOL_DB_PROD_NAME'] %>
  username: <%= ENV['EOL_DB_PROD_USERNAME'] %>
  password: <%= ENV['EOL_DB_PROD_PASSWORD'] %>