# PLEASE DON'T PUT YOUR USER / PASS HERE (e.g.: "root"). Modify your own config/secrets.yml

# common settings for all databases
common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: true
  wait_timeout: 300
  username: <%= Rails.application.secrets.db['username'] %>
  password: <%= Rails.application.secrets.db['password'] %>
  database: <%= Rails.application.secrets.db['name'] %>

# common settings for any development databases
development:
  <<: *common
  host: localhost

test: &test
  <<: *common
  host: localhost

staging:
  <<: *common
  host: <%= Rails.application.secrets.db['host'] %>
  port: <%= Rails.application.secrets.db['port'] %>

production:
  <<: *common
  host: <%= Rails.application.secrets.db['host'] %>
  port: <%= Rails.application.secrets.db['port'] %>
