# common settings for all databases
common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: true
  wait_timeout: 300

# common settings for any development databases
development:
  <<: *common
  host: localhost
  # PLEASE DON'T PUT YOUR USER / PASS HERE (e.g.: "root"). Set your environment
  # variables.
  username: root
  password: <%= ENV['database_pass'] %>
  database: eol_development

test: &test
  <<: *common
  database: eol_test
  host: localhost
  # PLEASE DON'T PUT YOUR USER / PASS HERE (e.g.: "root"). Set your environment
  # variables.
  username: <%= ENV['EOL_DB_DEVEL_USERNAME'] %>
  password: <%= ENV['EOL_DB_DEVEL_PASSWORD'] %>

staging:
  <<: *common
  host: <%= ENV['EOL_DB_HOST'] %>
  port: <%= ENV['EOL_DB_PORT'] %>
  database: <%= ENV['EOL_DB_STAGING_NAME'] %>
  username: <%= ENV['EOL_DB_STAGING_USERNAME'] %>
  password: <%= ENV['EOL_DB_STAGING_PASSWORD'] %>

production:
  <<: *common
  host: localhost
  database: eol_development
  username: root
  password: <%= ENV['database_pass'] %>
