# PLEASE DON'T PUT YOUR USER / PASS HERE (e.g.: "root"). Modify your own config/secrets.yml

# common settings for all databases
common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: true
  wait_timeout: 300
  local_infile: true
  username: root
  password: <%= ENV['database_pass'] %>

# common settings for any development databases
development:
  <<: *common
  host: localhost
  database: eol_development

test: &test
  <<: *common
  host: localhost

staging:
  <<: *common
  host: <%= ENV['EOL_DB_HOST'] %>
  port: <%= ENV['EOL_DB_PORT'] %>

production:
  <<: *common
  host: localhost
