# common settings for all databases
common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: true
  wait_timeout: 300

# common settings for any development databases
development:
  <<: *common
  host: localhost
  # PLEASE DON'T PUT YOUR USER / PASS HERE (e.g.: "root"). Use the secrets.yml file.
  database: <%= Rails.application.secrets.db.name %>
  username: <%= Rails.application.secrets.db.username %>
  password: <%= Rails.application.secrets.db.password %>

test: &test
  <<: *common
  database: eol_test
  host: localhost
  # PLEASE DON'T PUT YOUR USER / PASS HERE (e.g.: "root"). Use the secrets.yml file.
  database: <%= Rails.application.secrets.db.name %>
  username: <%= Rails.application.secrets.db.username %>
  password: <%= Rails.application.secrets.db.password %>

staging:
  <<: *common
  host: <%= Rails.application.secrets.db.host %>
  port: <%= Rails.application.secrets.db.port %>
  database: <%= Rails.application.secrets.db.name %>
  username: <%= Rails.application.secrets.db.username %>
  password: <%= Rails.application.secrets.db.password %>

production:
  <<: *common
  host: <%= Rails.application.secrets.db.host %>
  port: <%= Rails.application.secrets.db.port %>
  database: <%= Rails.application.secrets.db.name %>
  username: <%= Rails.application.secrets.db.username %>
  password: <%= Rails.application.secrets.db.password %>
