# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebd78e534a43248430010cf76f951ac7055577dc9dff146e6a74cc858b8128ec102dca4a6bfa03b5db29e5d3f2c9a3bd06c3cbd3ce1b1a8a1f897a0a3c5ffa06
  google_maps_key: <%= ENV["EOL_GOOGLE_MAPS_KEY"] || "google_maps_test_key" %>
  discourse_url: <%= ENV["EOL_DISCOURSE_URL"] || "" %>
  discourse_user: <%= ENV["EOL_DISCOURSE_USER"] || "" %>
  discourse_key: <%= ENV["EOL_DISCOURSE_KEY"] || "" %>

test:
  secret_key_base: 099f735bf94ab06af5dfe69e0fbb160a1a051053ecc5e68f983240d9c4b95581ce03ef61a44e18cc766368dde3b0695a1f14da0a6d39e96d827eb1bbe4565776
  google_maps_key: google_maps_test_key
  discourse_url: ""
  discourse_user: ""
  discourse_key: ""

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_key: <%= ENV["EOL_GOOGLE_MAPS_KEY"] %>
  discourse_url: <%= ENV["EOL_DISCOURSE_URL"] %>
  discourse_user: <%= ENV["EOL_DISCOURSE_USER"] %>
  discourse_key: <%= ENV["EOL_DISCOURSE_KEY"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_key: <%= ENV["EOL_GOOGLE_MAPS_KEY"] %>
  discourse_url: <%= ENV["EOL_DISCOURSE_URL"] %>
  discourse_user: <%= ENV["EOL_DISCOURSE_USER"] %>
  discourse_key: <%= ENV["EOL_DISCOURSE_KEY"] %>
